<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>The Analysis of South African Household Survey Data using R</title>
  <meta name="description" content="The Analysis of South African Household Survey Data using R">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="The Analysis of South African Household Survey Data using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="The Analysis of South African Household Survey Data using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="The Analysis of South African Household Survey Data using R" />
  
  <meta name="twitter:description" content="The Analysis of South African Household Survey Data using R" />
  

<meta name="author" content="Takwanisa Machemedze">


<meta name="date" content="2018-07-23">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="bivariate-analysis-cross-tabs.html">
<link rel="next" href="multiple-regression-analysis.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#what-is-r"><i class="fa fa-check"></i><b>1.1</b> What is R?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#pros-and-cons-of-r"><i class="fa fa-check"></i><b>1.2</b> Pros and cons of R</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#pros"><i class="fa fa-check"></i><b>1.2.1</b> Pros</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#cons"><i class="fa fa-check"></i><b>1.2.2</b> Cons</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#what-is-rstudio"><i class="fa fa-check"></i><b>1.3</b> What is RStudio?</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#the-r-system"><i class="fa fa-check"></i><b>1.4</b> The R system</a><ul>
<li class="chapter" data-level="1.4.1" data-path="introduction.html"><a href="introduction.html#base-system"><i class="fa fa-check"></i><b>1.4.1</b> Base system</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html"><i class="fa fa-check"></i><b>2</b> Getting started with R</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#organize-your-r-session"><i class="fa fa-check"></i><b>2.2</b> Organize your R session</a><ul>
<li class="chapter" data-level="2.2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#working-directory"><i class="fa fa-check"></i><b>2.2.1</b> Working directory</a></li>
<li class="chapter" data-level="2.2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#load-and-install-required-libraries"><i class="fa fa-check"></i><b>2.2.2</b> Load (and install) required libraries</a></li>
<li class="chapter" data-level="2.2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#comments"><i class="fa fa-check"></i><b>2.2.3</b> Comments</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#getting-help"><i class="fa fa-check"></i><b>2.3</b> Getting help</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#output-file"><i class="fa fa-check"></i><b>2.4</b> Output file</a></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#objects-in-r"><i class="fa fa-check"></i><b>2.5</b> Objects in R</a><ul>
<li class="chapter" data-level="2.5.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#removing-objects-from-the-r-environment---rm-function"><i class="fa fa-check"></i><b>2.5.1</b> Removing objects from the R environment - rm() function</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#saving-in-r"><i class="fa fa-check"></i><b>2.6</b> Saving in R</a></li>
<li class="chapter" data-level="2.7" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#importing-nids-data-into-r"><i class="fa fa-check"></i><b>2.7</b> Importing NIDS data into R</a></li>
<li class="chapter" data-level="2.8" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#exploring-the-data"><i class="fa fa-check"></i><b>2.8</b> Exploring the data</a><ul>
<li class="chapter" data-level="2.8.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#subsetting-data---part-1"><i class="fa fa-check"></i><b>2.8.1</b> Subsetting data - part 1</a></li>
<li class="chapter" data-level="2.8.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#data-documentation---value-and-variable-labels"><i class="fa fa-check"></i><b>2.8.2</b> Data documentation - value and variable labels</a></li>
<li class="chapter" data-level="2.8.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#operators-in-r"><i class="fa fa-check"></i><b>2.8.3</b> Operators in R</a></li>
<li class="chapter" data-level="2.8.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#subsetting-data---part-2"><i class="fa fa-check"></i><b>2.8.4</b> Subsetting data - part 2</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#tidyverse"><i class="fa fa-check"></i><b>2.9</b> Tidyverse</a><ul>
<li class="chapter" data-level="2.9.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#brief-introduction-to-tidyverse"><i class="fa fa-check"></i><b>2.9.1</b> Brief introduction to tidyverse</a></li>
<li class="chapter" data-level="2.9.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#core-tidyverse-packages"><i class="fa fa-check"></i><b>2.9.2</b> Core tidyverse packages</a></li>
<li class="chapter" data-level="2.9.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#install-and-load-tidyverse-packages"><i class="fa fa-check"></i><b>2.9.3</b> Install and load tidyverse packages</a></li>
<li class="chapter" data-level="2.9.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#dplyr-verbs"><i class="fa fa-check"></i><b>2.9.4</b> dplyr verbs</a></li>
<li class="chapter" data-level="2.9.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#using-dplyr-functions"><i class="fa fa-check"></i><b>2.9.5</b> Using dplyr functions</a></li>
<li class="chapter" data-level="2.9.6" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#pipe-operator"><i class="fa fa-check"></i><b>2.9.6</b> Pipe operator %&gt;%</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#more-data-exploration"><i class="fa fa-check"></i><b>2.10</b> More data exploration</a><ul>
<li class="chapter" data-level="2.10.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#example-1-subset-variables"><i class="fa fa-check"></i><b>2.10.1</b> Example 1: Subset variables</a></li>
<li class="chapter" data-level="2.10.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#example-2-subset-observations"><i class="fa fa-check"></i><b>2.10.2</b> Example 2: Subset observations</a></li>
<li class="chapter" data-level="2.10.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#example-3-subset-both-observations-and-variables"><i class="fa fa-check"></i><b>2.10.3</b> Example 3: Subset both observations and variables</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#managing-the-data"><i class="fa fa-check"></i><b>2.11</b> Managing the data</a></li>
<li class="chapter" data-level="2.12" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#worked-example-creating-a-bmi-variable"><i class="fa fa-check"></i><b>2.12</b> Worked example: creating a bmi variable</a></li>
<li class="chapter" data-level="2.13" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#question-answers"><i class="fa fa-check"></i><b>2.13</b> Question answers</a></li>
<li class="chapter" data-level="2.14" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#exercises"><i class="fa fa-check"></i><b>2.14</b> Exercises</a></li>
<li class="chapter" data-level="2.15" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#exercise-answers"><i class="fa fa-check"></i><b>2.15</b> Exercise answers</a></li>
<li class="chapter" data-level="2.16" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#session-information"><i class="fa fa-check"></i><b>2.16</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="understanding-distributions.html"><a href="understanding-distributions.html"><i class="fa fa-check"></i><b>3</b> Understanding distributions</a><ul>
<li class="chapter" data-level="3.1" data-path="understanding-distributions.html"><a href="understanding-distributions.html#introduction-2"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="understanding-distributions.html"><a href="understanding-distributions.html#variable-types"><i class="fa fa-check"></i><b>3.2</b> Variable types</a></li>
<li class="chapter" data-level="3.3" data-path="understanding-distributions.html"><a href="understanding-distributions.html#count-observations---dimnrow"><i class="fa fa-check"></i><b>3.3</b> Count observations - dim(),nrow()</a></li>
<li class="chapter" data-level="3.4" data-path="understanding-distributions.html"><a href="understanding-distributions.html#using-household-level-variables"><i class="fa fa-check"></i><b>3.4</b> Using household level variables</a></li>
<li class="chapter" data-level="3.5" data-path="understanding-distributions.html"><a href="understanding-distributions.html#frequency-distribution-tables"><i class="fa fa-check"></i><b>3.5</b> Frequency distribution tables</a></li>
<li class="chapter" data-level="3.6" data-path="understanding-distributions.html"><a href="understanding-distributions.html#frequency-distribution-tables-household-level-data"><i class="fa fa-check"></i><b>3.6</b> Frequency distribution tables: household level data</a></li>
<li class="chapter" data-level="3.7" data-path="understanding-distributions.html"><a href="understanding-distributions.html#missing-data-and-non-responses"><i class="fa fa-check"></i><b>3.7</b> Missing data and non-responses</a></li>
<li class="chapter" data-level="3.8" data-path="understanding-distributions.html"><a href="understanding-distributions.html#three-primary-origins-of-na-missing-data-in-nids"><i class="fa fa-check"></i><b>3.8</b> Three primary origins of NA-missing data in NIDS</a></li>
<li class="chapter" data-level="3.9" data-path="understanding-distributions.html"><a href="understanding-distributions.html#missing-data-and-qualifiers"><i class="fa fa-check"></i><b>3.9</b> Missing data and qualifiers</a></li>
<li class="chapter" data-level="3.10" data-path="understanding-distributions.html"><a href="understanding-distributions.html#question-answers-1"><i class="fa fa-check"></i><b>3.10</b> Question answers</a></li>
<li class="chapter" data-level="3.11" data-path="understanding-distributions.html"><a href="understanding-distributions.html#exercises-1"><i class="fa fa-check"></i><b>3.11</b> Exercises</a></li>
<li class="chapter" data-level="3.12" data-path="understanding-distributions.html"><a href="understanding-distributions.html#session-information-1"><i class="fa fa-check"></i><b>3.12</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="understanding-graphs.html"><a href="understanding-graphs.html"><i class="fa fa-check"></i><b>4</b> Understanding graphs</a><ul>
<li class="chapter" data-level="4.1" data-path="understanding-graphs.html"><a href="understanding-graphs.html#introduction-3"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="understanding-graphs.html"><a href="understanding-graphs.html#getting-ready"><i class="fa fa-check"></i><b>4.2</b> Getting ready</a></li>
<li class="chapter" data-level="4.3" data-path="understanding-graphs.html"><a href="understanding-graphs.html#ggplot2-and-its-elements"><i class="fa fa-check"></i><b>4.3</b> ggplot2 and its elements</a></li>
<li class="chapter" data-level="4.4" data-path="understanding-graphs.html"><a href="understanding-graphs.html#histograms"><i class="fa fa-check"></i><b>4.4</b> Histograms</a><ul>
<li class="chapter" data-level="4.4.1" data-path="understanding-graphs.html"><a href="understanding-graphs.html#graphing-economic-wellbeing-in-south-africa-in-2008"><i class="fa fa-check"></i><b>4.4.1</b> Graphing economic wellbeing in South Africa in 2008</a></li>
<li class="chapter" data-level="4.4.2" data-path="understanding-graphs.html"><a href="understanding-graphs.html#facetting"><i class="fa fa-check"></i><b>4.4.2</b> Facetting</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="understanding-graphs.html"><a href="understanding-graphs.html#worked-example-1-what-is-the-most-common-age-at-which-people-start-smoking"><i class="fa fa-check"></i><b>4.5</b> Worked example 1: What is the most common age at which people start smoking?</a></li>
<li class="chapter" data-level="4.6" data-path="understanding-graphs.html"><a href="understanding-graphs.html#pie-charts"><i class="fa fa-check"></i><b>4.6</b> Pie charts</a></li>
<li class="chapter" data-level="4.7" data-path="understanding-graphs.html"><a href="understanding-graphs.html#investigating-newborn-and-infant-gender"><i class="fa fa-check"></i><b>4.7</b> Investigating newborn and infant gender</a><ul>
<li class="chapter" data-level="4.7.1" data-path="understanding-graphs.html"><a href="understanding-graphs.html#exploring-the-distribution-of-race-across-provinces"><i class="fa fa-check"></i><b>4.7.1</b> Exploring the distribution of race across provinces</a></li>
<li class="chapter" data-level="4.7.2" data-path="understanding-graphs.html"><a href="understanding-graphs.html#urban-vs.rural-where-are-south-africans-living"><i class="fa fa-check"></i><b>4.7.2</b> Urban vs. rural, where are South Africans living?</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="understanding-graphs.html"><a href="understanding-graphs.html#worked-example-2-are-there-differences-between-the-age-at-which-men-and-women-start-smoking"><i class="fa fa-check"></i><b>4.8</b> Worked example 2: Are there differences between the age at which men and women start smoking?</a><ul>
<li class="chapter" data-level="4.8.1" data-path="understanding-graphs.html"><a href="understanding-graphs.html#exercise"><i class="fa fa-check"></i><b>4.8.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="understanding-graphs.html"><a href="understanding-graphs.html#bar-graphs"><i class="fa fa-check"></i><b>4.9</b> Bar graphs</a><ul>
<li class="chapter" data-level="4.9.1" data-path="understanding-graphs.html"><a href="understanding-graphs.html#investigating-satisfaction-levels-in-south-africans"><i class="fa fa-check"></i><b>4.9.1</b> Investigating Satisfaction levels in South Africans</a></li>
<li class="chapter" data-level="4.9.2" data-path="understanding-graphs.html"><a href="understanding-graphs.html#worked-example-3-does-the-frequency-of-alcohol-consumption-vary-by-gender-race-or-religion"><i class="fa fa-check"></i><b>4.9.2</b> Worked example 3: Does the frequency of alcohol consumption vary by gender, race or religion?</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="understanding-graphs.html"><a href="understanding-graphs.html#question-answers-2"><i class="fa fa-check"></i><b>4.10</b> Question answers</a></li>
<li class="chapter" data-level="4.11" data-path="understanding-graphs.html"><a href="understanding-graphs.html#session-information-2"><i class="fa fa-check"></i><b>4.11</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html"><i class="fa fa-check"></i><b>5</b> Measures of central tendency and variability</a><ul>
<li class="chapter" data-level="5.1" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#getting-ready-1"><i class="fa fa-check"></i><b>5.1</b> Getting ready</a></li>
<li class="chapter" data-level="5.2" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#introduction-4"><i class="fa fa-check"></i><b>5.2</b> Introduction</a></li>
<li class="chapter" data-level="5.3" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#understanding-distributions-of-continuous-variables"><i class="fa fa-check"></i><b>5.3</b> Understanding distributions of continuous variables</a></li>
<li class="chapter" data-level="5.4" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#continuous-variables-and-recoding"><i class="fa fa-check"></i><b>5.4</b> Continuous variables and recoding</a></li>
<li class="chapter" data-level="5.5" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#summarise-by---summary-base-r-and-group_by---summarise-dplyr"><i class="fa fa-check"></i><b>5.5</b> Summarise: by - summary (base R) and group_by - summarise (dplyr)</a></li>
<li class="chapter" data-level="5.6" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#medians-and-modes-of-continuous-variables"><i class="fa fa-check"></i><b>5.6</b> Medians and modes of continuous variables</a></li>
<li class="chapter" data-level="5.7" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#example-recoding-the-education-variable"><i class="fa fa-check"></i><b>5.7</b> Example: recoding the education variable</a></li>
<li class="chapter" data-level="5.8" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#measures-of-dispersion---variance-and-standard-deviation"><i class="fa fa-check"></i><b>5.8</b> Measures of dispersion - variance and standard deviation</a></li>
<li class="chapter" data-level="5.9" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#handling-outliers"><i class="fa fa-check"></i><b>5.9</b> Handling outliers</a></li>
<li class="chapter" data-level="5.10" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#understanding-the-distributions-of-categorical-variables"><i class="fa fa-check"></i><b>5.10</b> Understanding the distributions of categorical variables</a></li>
<li class="chapter" data-level="5.11" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#worked-example-1-exploring-the-distribution-of-satisfaction-variable"><i class="fa fa-check"></i><b>5.11</b> Worked example 1: Exploring the distribution of satisfaction variable</a></li>
<li class="chapter" data-level="5.12" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#group-summary"><i class="fa fa-check"></i><b>5.12</b> Group summary</a></li>
<li class="chapter" data-level="5.13" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#worked-example-2-investigating-bmi-in-south-africa"><i class="fa fa-check"></i><b>5.13</b> Worked example 2: Investigating BMI in South Africa</a></li>
<li class="chapter" data-level="5.14" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#question-answers-3"><i class="fa fa-check"></i><b>5.14</b> Question answers</a></li>
<li class="chapter" data-level="5.15" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#exercises-2"><i class="fa fa-check"></i><b>5.15</b> Exercises</a></li>
<li class="chapter" data-level="5.16" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#exercise-answers-1"><i class="fa fa-check"></i><b>5.16</b> Exercise answers</a></li>
<li class="chapter" data-level="5.17" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#exercises-3"><i class="fa fa-check"></i><b>5.17</b> Exercises</a></li>
<li class="chapter" data-level="5.18" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#exercise-answers-2"><i class="fa fa-check"></i><b>5.18</b> Exercise answers</a></li>
<li class="chapter" data-level="5.19" data-path="measures-of-central-tendency-and-variability.html"><a href="measures-of-central-tendency-and-variability.html#session-information-3"><i class="fa fa-check"></i><b>5.19</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html"><i class="fa fa-check"></i><b>6</b> Bivariate analysis (cross tabs)</a><ul>
<li class="chapter" data-level="6.1" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#getting-ready-2"><i class="fa fa-check"></i><b>6.1</b> Getting ready</a></li>
<li class="chapter" data-level="6.2" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#introduction-5"><i class="fa fa-check"></i><b>6.2</b> Introduction</a></li>
<li class="chapter" data-level="6.3" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#cross---tabulation"><i class="fa fa-check"></i><b>6.3</b> Cross - tabulation</a></li>
<li class="chapter" data-level="6.4" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#example-1-where-do-households-with-an-elderly-member-tend-to-live"><i class="fa fa-check"></i><b>6.4</b> Example 1: Where do households with an elderly member tend to live?</a></li>
<li class="chapter" data-level="6.5" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#example-2-is-there-a-relationship-between-the-race-of-a-household-and-the-average-age-of-the-household"><i class="fa fa-check"></i><b>6.5</b> Example 2: Is there a relationship between the race of a household and the average age of the household?</a></li>
<li class="chapter" data-level="6.6" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#example-3-does-the-level-of-satisfaction-differ-in-different-racegender-groupings"><i class="fa fa-check"></i><b>6.6</b> Example 3: Does the level of satisfaction differ in different race/gender groupings?</a></li>
<li class="chapter" data-level="6.7" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#example-4-comparing-household-monthly-income-from-the-labour-market-to-individual-monthly-takehome-pay"><i class="fa fa-check"></i><b>6.7</b> Example 4: Comparing Household Monthly Income from the labour market to individual monthly takehome pay</a></li>
<li class="chapter" data-level="6.8" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#chi-squared-testing-for-independence"><i class="fa fa-check"></i><b>6.8</b> Chi-Squared: testing for independence</a></li>
<li class="chapter" data-level="6.9" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#cross-tabs-and-hypothesis-testing-chi2-examples-the-comparative-level-of-happiness-variable"><i class="fa fa-check"></i><b>6.9</b> Cross-tabs and hypothesis testing (Chi^2) examples: The comparative level of happiness variable</a><ul>
<li class="chapter" data-level="6.9.1" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#example-1-comparative-happiness-and-employment-status"><i class="fa fa-check"></i><b>6.9.1</b> Example 1: Comparative happiness and employment status</a></li>
<li class="chapter" data-level="6.9.2" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#example-2-comparative-happiness-by-province"><i class="fa fa-check"></i><b>6.9.2</b> Example 2: Comparative happiness by province</a></li>
<li class="chapter" data-level="6.9.3" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#example-3-comparative-happiness-and-household-income"><i class="fa fa-check"></i><b>6.9.3</b> Example 3: Comparative happiness and household income</a></li>
<li class="chapter" data-level="6.9.4" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#example-4-comparative-happiness-and-geo-type"><i class="fa fa-check"></i><b>6.9.4</b> Example 4: Comparative happiness and geo-type</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#worked-example-assessing-the-impact-of-per-capita-income-on-bmi"><i class="fa fa-check"></i><b>6.10</b> Worked Example: Assessing the impact of per capita income on BMI</a></li>
<li class="chapter" data-level="6.11" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#question-answers-4"><i class="fa fa-check"></i><b>6.11</b> Question Answers</a></li>
<li class="chapter" data-level="6.12" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#exercises-4"><i class="fa fa-check"></i><b>6.12</b> Exercises</a></li>
<li class="chapter" data-level="6.13" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#exercise-answers-3"><i class="fa fa-check"></i><b>6.13</b> Exercise answers</a></li>
<li class="chapter" data-level="6.14" data-path="bivariate-analysis-cross-tabs.html"><a href="bivariate-analysis-cross-tabs.html#session-information-4"><i class="fa fa-check"></i><b>6.14</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html"><i class="fa fa-check"></i><b>7</b> Simple regression analysis</a><ul>
<li class="chapter" data-level="7.1" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#getting-ready-3"><i class="fa fa-check"></i><b>7.1</b> Getting ready</a></li>
<li class="chapter" data-level="7.2" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#introduction-6"><i class="fa fa-check"></i><b>7.2</b> Introduction</a></li>
<li class="chapter" data-level="7.3" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#correlation-of-variables"><i class="fa fa-check"></i><b>7.3</b> Correlation of variables</a></li>
<li class="chapter" data-level="7.4" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#outliers"><i class="fa fa-check"></i><b>7.4</b> Outliers</a></li>
<li class="chapter" data-level="7.5" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#simple-regression"><i class="fa fa-check"></i><b>7.5</b> Simple regression</a></li>
<li class="chapter" data-level="7.6" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#understanding-regression-output-tables"><i class="fa fa-check"></i><b>7.6</b> Understanding regression output tables</a></li>
<li class="chapter" data-level="7.7" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#graphing-the-regression-equation"><i class="fa fa-check"></i><b>7.7</b> Graphing the regression equation</a></li>
<li class="chapter" data-level="7.8" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#worked-example-is-age-a-strong-determinant-of-bmi"><i class="fa fa-check"></i><b>7.8</b> Worked example: Is age a strong determinant of BMI?</a></li>
<li class="chapter" data-level="7.9" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#question-answers-5"><i class="fa fa-check"></i><b>7.9</b> Question answers:</a></li>
<li class="chapter" data-level="7.10" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#exercises-5"><i class="fa fa-check"></i><b>7.10</b> Exercises</a></li>
<li class="chapter" data-level="7.11" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#exercise-1"><i class="fa fa-check"></i><b>7.11</b> Exercise</a></li>
<li class="chapter" data-level="7.12" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#exercise-answers-4"><i class="fa fa-check"></i><b>7.12</b> Exercise answers</a></li>
<li class="chapter" data-level="7.13" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#appendix-a-analysis-of-variance-anova-table"><i class="fa fa-check"></i><b>7.13</b> Appendix A: Analysis of variance (anova) table</a></li>
<li class="chapter" data-level="7.14" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#appendix-b-further-understanding-the-regression-results-table"><i class="fa fa-check"></i><b>7.14</b> Appendix B: Further understanding the regression results table</a></li>
<li class="chapter" data-level="7.15" data-path="simple-regression-analysis.html"><a href="simple-regression-analysis.html#session-information-5"><i class="fa fa-check"></i><b>7.15</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html"><i class="fa fa-check"></i><b>8</b> Multiple regression analysis</a><ul>
<li class="chapter" data-level="8.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#getting-ready-4"><i class="fa fa-check"></i><b>8.1</b> Getting ready</a></li>
<li class="chapter" data-level="8.2" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#introduction-7"><i class="fa fa-check"></i><b>8.2</b> Introduction</a></li>
<li class="chapter" data-level="8.3" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#dummy-variables"><i class="fa fa-check"></i><b>8.3</b> Dummy variables</a></li>
<li class="chapter" data-level="8.4" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#interactions-with-dummy-variables"><i class="fa fa-check"></i><b>8.4</b> Interactions with dummy Variables</a></li>
<li class="chapter" data-level="8.5" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#linear-transformations-of-non-linear-relationships"><i class="fa fa-check"></i><b>8.5</b> Linear transformations of non-linear relationships</a></li>
<li class="chapter" data-level="8.6" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#question-answers-6"><i class="fa fa-check"></i><b>8.6</b> Question Answers</a></li>
<li class="chapter" data-level="8.7" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#exercises-6"><i class="fa fa-check"></i><b>8.7</b> Exercises</a></li>
<li class="chapter" data-level="8.8" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#exercise-answers-5"><i class="fa fa-check"></i><b>8.8</b> Exercise answers</a></li>
<li class="chapter" data-level="8.9" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#session-information-6"><i class="fa fa-check"></i><b>8.9</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="further-analysis-and-useful-online-resources.html"><a href="further-analysis-and-useful-online-resources.html"><i class="fa fa-check"></i><b>9</b> Further analysis and useful online resources</a><ul>
<li class="chapter" data-level="9.1" data-path="further-analysis-and-useful-online-resources.html"><a href="further-analysis-and-useful-online-resources.html#further-analyses"><i class="fa fa-check"></i><b>9.1</b> Further analyses</a></li>
<li class="chapter" data-level="9.2" data-path="further-analysis-and-useful-online-resources.html"><a href="further-analysis-and-useful-online-resources.html#useful-online-resources"><i class="fa fa-check"></i><b>9.2</b> Useful online resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The Analysis of South African Household Survey Data using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-regression-analysis" class="section level1">
<h1><span class="header-section-number">7</span> Simple regression analysis</h1>
<div id="getting-ready-3" class="section level2">
<h2><span class="header-section-number">7.1</span> Getting ready</h2>
<p>In the previous chapters we generated some variables and ran some commands that will influence the results that we get in this chapter. If you are starting a new session of R, please copy the following lines of code into the R script editor and then run it before you begin the chapter. Make sure that you remember what each line of code is doing.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(foreign)
<span class="kw">library</span>(tidyverse)</code></pre></div>
<pre><code>## -- Attaching packages --------</code></pre>
<pre><code>## v ggplot2 3.0.0     v purrr   0.2.5
## v tibble  1.4.2     v dplyr   0.7.6
## v tidyr   0.8.1     v stringr 1.3.1
## v readr   1.1.1     v forcats 0.3.0</code></pre>
<pre><code>## -- Conflicts -----------------
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nids&lt;-<span class="kw">read.dta</span>(<span class="st">&quot;./data/nids.dta&quot;</span>, <span class="dt">convert.factors=</span><span class="ot">FALSE</span>)

nids&lt;-nids<span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">arrange</span>(hhid, pid)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(hhid) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">hhrestrict =</span> <span class="dv">1</span><span class="op">:</span><span class="kw">n</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">hhrestrict =</span> <span class="kw">ifelse</span>(hhrestrict<span class="op">==</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>))


<span class="co">#Class</span>
nids<span class="op">$</span>class&lt;-<span class="ot">NA</span>
nids<span class="op">$</span>class[<span class="kw">which</span>(nids<span class="op">$</span>w1_fwag<span class="op">&lt;=</span><span class="dv">1500</span>)]&lt;-<span class="dv">1</span>
nids<span class="op">$</span>class[<span class="kw">which</span>(nids<span class="op">$</span>w1_fwag<span class="op">&gt;</span><span class="dv">1500</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_fwag<span class="op">&lt;=</span><span class="dv">4500</span>)]&lt;-<span class="dv">2</span>
nids<span class="op">$</span>class[<span class="kw">which</span>(nids<span class="op">$</span>w1_fwag<span class="op">&gt;</span><span class="dv">4500</span>)]&lt;-<span class="dv">3</span>

nids<span class="op">$</span>class&lt;-<span class="kw">factor</span>(nids<span class="op">$</span>class, <span class="dt">levels=</span><span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Lower Class&quot;</span>,<span class="st">&quot;Middle Class&quot;</span>,<span class="st">&quot;Upper Class&quot;</span>))


###Creating a BMI variable - from chapter 2 ***

<span class="co">#Height</span>
nids&lt;-nids <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">height =</span> <span class="kw">ifelse</span> (w1_a_n1_<span class="dv">1</span> <span class="op">&gt;=</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span><span class="st"> </span>w1_a_best_age_yrs <span class="op">&gt;=</span><span class="st"> </span><span class="dv">20</span>, w1_a_n1_<span class="dv">1</span><span class="op">/</span><span class="dv">100</span>, <span class="ot">NA</span>))

<span class="co">#Weight</span>
nids&lt;-nids <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">weight =</span> <span class="kw">ifelse</span> (w1_a_n2_<span class="dv">1</span> <span class="op">&gt;=</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span><span class="st"> </span>w1_a_best_age_yrs <span class="op">&gt;</span><span class="st"> </span><span class="dv">20</span>, w1_a_n2_<span class="dv">1</span>, <span class="ot">NA</span>)) 

<span class="co">#BMI</span>
nids&lt;-nids <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">bmi =</span> weight<span class="op">/</span>height<span class="op">^</span><span class="dv">2</span>)

<span class="co">#Valid BMI values</span>
nids&lt;-nids<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">bmi_valid =</span> <span class="kw">ifelse</span>(bmi <span class="op">&gt;</span><span class="st"> </span><span class="dv">15</span> <span class="op">&amp;</span><span class="st"> </span>bmi <span class="op">&lt;</span><span class="st"> </span><span class="dv">50</span>,<span class="dv">1</span>,<span class="ot">NA</span>))

<span class="co">#BMI bins</span>
nids<span class="op">$</span>bmi.bins.nolabel&lt;-<span class="ot">NA</span>
nids<span class="op">$</span>bmi.bins.nolabel[<span class="kw">which</span>(nids<span class="op">$</span>bmi<span class="op">&gt;=</span><span class="dv">15</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>bmi<span class="op">&lt;</span><span class="fl">18.5</span>)]&lt;-<span class="dv">1</span>
nids<span class="op">$</span>bmi.bins.nolabel[<span class="kw">which</span>(nids<span class="op">$</span>bmi<span class="op">&gt;=</span><span class="fl">18.5</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>bmi<span class="op">&lt;</span><span class="dv">25</span>)]&lt;-<span class="dv">2</span>
nids<span class="op">$</span>bmi.bins.nolabel[<span class="kw">which</span>(nids<span class="op">$</span>bmi<span class="op">&gt;=</span><span class="dv">25</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>bmi<span class="op">&lt;</span><span class="dv">30</span>)]&lt;-<span class="dv">3</span>
nids<span class="op">$</span>bmi.bins.nolabel[<span class="kw">which</span>(nids<span class="op">$</span>bmi<span class="op">&gt;=</span><span class="dv">30</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>bmi<span class="op">&lt;=</span><span class="dv">50</span>)]&lt;-<span class="dv">4</span>

nids<span class="op">$</span>bmi.bins&lt;-<span class="kw">factor</span>(nids<span class="op">$</span>bmi.bins.nolabel, <span class="dt">levels=</span><span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Underweight&quot;</span>,<span class="st">&quot;Normal&quot;</span>, <span class="st">&quot;Overweight&quot;</span>, <span class="st">&quot;Obese&quot;</span>))

<span class="co">#Age</span>
nids&lt;-nids<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_adult =</span> <span class="kw">ifelse</span>(w1_a_best_age_yrs<span class="op">&lt;</span><span class="dv">0</span>,<span class="ot">NA</span>, w1_a_best_age_yrs))

<span class="co">#Age bins</span>
nids<span class="op">$</span>age_bins&lt;-<span class="ot">NA</span>
nids<span class="op">$</span>age_bins[<span class="kw">which</span>(nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&gt;=</span><span class="dv">20</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&lt;=</span><span class="dv">29</span>)]&lt;-<span class="dv">1</span>
nids<span class="op">$</span>age_bins[<span class="kw">which</span>(nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&gt;</span><span class="dv">29</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&lt;=</span><span class="dv">39</span>)]&lt;-<span class="dv">2</span>
nids<span class="op">$</span>age_bins[<span class="kw">which</span>(nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&gt;</span><span class="dv">39</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&lt;=</span><span class="dv">49</span>)]&lt;-<span class="dv">3</span>
nids<span class="op">$</span>age_bins[<span class="kw">which</span>(nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&gt;</span><span class="dv">49</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&lt;=</span><span class="dv">59</span>)]&lt;-<span class="dv">4</span>
nids<span class="op">$</span>age_bins[<span class="kw">which</span>(nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&gt;</span><span class="dv">59</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&lt;=</span><span class="dv">69</span>)]&lt;-<span class="dv">5</span>
nids<span class="op">$</span>age_bins[<span class="kw">which</span>(nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&gt;</span><span class="dv">69</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_r_best_age_yrs<span class="op">&lt;=</span><span class="dv">120</span>)]&lt;-<span class="dv">6</span>

nids<span class="op">$</span>age_bins &lt;-<span class="st"> </span><span class="kw">factor</span>(nids<span class="op">$</span>age_bins, <span class="dt">levels =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;20 - 29 yrs&quot;</span>,<span class="st">&quot;30 - 39 yrs&quot;</span>, <span class="st">&quot;40 - 49 yrs&quot;</span>, <span class="st">&quot;50 - 59 yrs&quot;</span>, <span class="st">&quot;60 - 69 yrs&quot;</span>, <span class="st">&quot;70 - 120 yrs&quot;</span>))

<span class="co">#Rename</span>
nids &lt;-<span class="st"> </span>nids<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">race =</span> w1_best_race,
        <span class="dt">age =</span> w1_r_best_age_yrs,
        <span class="dt">gender =</span> w1_r_b4,
        <span class="dt">province =</span> w1_hhprov, 
        <span class="dt">hhincome =</span> w1_hhincome) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">gender =</span> <span class="kw">factor</span>(gender, <span class="dt">levels =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>)),
         <span class="dt">race =</span> <span class="kw">factor</span>(race, <span class="dt">levels =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;African&quot;</span>, <span class="st">&quot;Coloured&quot;</span>,<span class="st">&quot;Asian&quot;</span>, <span class="st">&quot;White&quot;</span>)),
         <span class="dt">province =</span> <span class="kw">factor</span>(province, <span class="dt">levels=</span><span class="dv">1</span><span class="op">:</span><span class="dv">9</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Western Cape&quot;</span>,<span class="st">&quot;Eastern Cape&quot;</span>,<span class="st">&quot;Northern Cape&quot;</span>,<span class="st">&quot;Free State&quot;</span>,<span class="st">&quot;KwaZulu-Natal&quot;</span>,<span class="st">&quot;North West&quot;</span>,<span class="st">&quot;Gauteng&quot;</span>,<span class="st">&quot;Mpumalanga&quot;</span>,<span class="st">&quot;Limpopo&quot;</span>)),
         <span class="dt">w1_hhgeo =</span> <span class="kw">factor</span>(w1_hhgeo, <span class="dt">levels =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Rural formal&quot;</span>, <span class="st">&quot;Tribal authority areas&quot;</span>,<span class="st">&quot;Urban formal&quot;</span>, <span class="st">&quot;Urban informal&quot;</span>)))</code></pre></div>
</div>
<div id="introduction-6" class="section level2">
<h2><span class="header-section-number">7.2</span> Introduction</h2>
<p>In Chapter 6, you learned methods in R that allowed you to determine whether two variables were statistically related or independent of one another. While this is indeed important, it is often necessary to take your analysis a few steps further to determine the actual relationship between variables.</p>
<p>In this <em>Simple Regression Chapter</em>, we will cover the first two methods commonly used to determine the relationship between two variables. The first is correlation analysis, which simply measures the strength or degree of association between two continuous variables. The second is <em>simple regression analysis</em>, which allows us to determine how one variable changes in relation to a change in another variable.</p>
<p>In regression analysis, we are often interested in causal relationships. For example, we could be interested in whether political participation depends on individual income? Or we could be interested in whether product advertisement on the Internet leads to higher sales? In general, we are interested in whether variable X has an effect on variable Y. As such, it is often useful to think of variable X as the “independent” or “explanatory” variable and to think of variable Y as the “dependent” variable or as the “effect”. However, it is important to note that a regression tests only for an association between the movements of two variables and does not tell us whether one of the variables causes the other.</p>
<p>In this chapter, we will concentrate on the relationship between total monthly household expenditures (<code>w1_h_expenditure</code>) and total monthly household income (<code>w1_hhincome</code>). Do you think that one of these two variables exerts a causal influence on the other? We might hypothesize that there is a strong causal link between a household’s income and the amount they spend. It makes sense that the more money you receive, the more you will spend. It is your hypothesis which tells you which variable should be your independent variable and which should be your dependent variable.</p>
<p>According to our hypothesis that income has a causal effect on expenditure, expenditure will be the <strong>dependent</strong> variable and income will be the <strong>independent</strong> variable. Once we have used theory and logical reasoning to decide on our hypothesis, we use a regression to test whether there is indeed an association between the relevant variables. And further, to determine the magnitude of the relationship. Below, we will test whether a higher income will be associated with a higher level of expenditure. If it does, we will try to determine how much more a household spends when their income increases.</p>
<p>Since the two variables that we are interested in (<code>w1_h_expenditure</code> and <code>w1_hhincome</code>) are household-level variables, the first thing that we want to do is to limit the observations to one per household. As we have done in the previous chapters, we need to be careful to use only one observation per household; otherwise we will have the problem of multiple counting. This would lead to larger households having a greater influence on the results than smaller households.</p>
<p>For now, let’s concentrate on the first method we mentioned, correlation analysis. Then we will proceed on to simple regression.</p>
</div>
<div id="correlation-of-variables" class="section level2">
<h2><span class="header-section-number">7.3</span> Correlation of variables</h2>
<p>Suppose someone made the statement, “Households that earn 6,000 Rand spend more than households that earn 3,000.” This sounds like a reasonable statement to make, however, being the researchers that we are; we want to confirm our intuition with empirical facts. Since we are dealing with two continuous variables and we want to test whether there is a linear relationship (i.e. that a R1 increase in income causes a constant increase in expenditure, regardless of the person’s income level), the appropriate measure of association is a Pearson correlation which in R performs with the <code>cor</code> command from the <code>stats</code> package.</p>
<p>Note, even if we don’t find a linear relationship, this does not mean the variables are not related. For instance, in this scenario, you might contend that someone who moves from an income of R100 to R150 will probably spend the entire R50 increase, while someone who moves from an income of R10 000 to R10 050 is more likely to save a portion of the R50. If this is the case, then the relationship may be non-linear (the effect of an increase in income on expenditure is different at different income levels). Nevertheless, testing for a linear relationship is generally a very good starting point for analysis.</p>
<p>The Pearson correlation measures the degree to which variables are related or in other words, the degree to which they co-vary. As mentioned above, when using correlation in our analysis, we must make the assumption that the relationship between our two variables is linear. If we suspect otherwise, we should make the proper adjustments to the variable that does not meet the assumption (we will cover this in more detail in Chapter 8). Overall, the initial use of the correlation coefficient is a good way to start investigating whether your intuition about a relationship is remotely correct.</p>
<p>(Notice how we use our <code>hhrestrict</code> dummy variable to ensure only one observation per household)</p>
<p>R produces the following results:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(nids[nids<span class="op">$</span>hhrestrict<span class="op">==</span><span class="dv">1</span>,<span class="kw">c</span>(<span class="st">&quot;w1_hhincome&quot;</span>,<span class="st">&quot;w1_h_expenditure&quot;</span>)], <span class="dt">use=</span><span class="st">&quot;complete.obs&quot;</span>)</code></pre></div>
<pre><code>##                  w1_hhincome w1_h_expenditure
## w1_hhincome         1.000000         0.689326
## w1_h_expenditure    0.689326         1.000000</code></pre>
<p>Or pipe using <code>dplyr</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nids <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(hhrestrict<span class="op">==</span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(w1_hhincome,w1_h_expenditure) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">cor</span>() <span class="co">#check cor arguments if you want to change the default</span></code></pre></div>
<pre><code>##                  w1_hhincome w1_h_expenditure
## w1_hhincome         1.000000         0.689326
## w1_h_expenditure    0.689326         1.000000</code></pre>
<p>R produces the above table, but what does it mean? A correlation value can range from -1 to +1, with 0 indicating that there is no linear association and ±1 being a perfect linear association. If the correlation value is low (near 0), there may still be a non-linear association between the variables of interest.</p>
<p>In our example, you will notice that the coefficient 0.6893 is relatively large and positive. This means that the linear association between our two variables is relatively strong. Thus, as the values of <code>w1_h_expenditure</code> increase, so do the <code>w1_hhincome</code> values. More clearly, households with a higher total monthly income tend to also have higher total monthly expenditures.</p>
<p>Let’s get back to the original statement, “Households that earn 6,000 Rand spend more than households that earn 3,000.” Our initial study of the matter suggests that this is likely to be true, according to our R correlation calculations. This initial approach, however, is too simplistic. R can do much more. We can go further and figure out by exactly how much total monthly household income influences total monthly household expenditure. To do this, we can fit a linear model using the <code>lm()</code> command. Before we move on, however, try the following questions:</p>
<p><strong>1. What the correlation between the average household’s food expenditure and household size?</strong></p>
<p>Question 1 Answer</p>
</div>
<div id="outliers" class="section level2">
<h2><span class="header-section-number">7.4</span> Outliers</h2>
<p>Before we continue on to simple regression analysis, it is a good idea to spend a few minutes reviewing the issue of outliers again. We must be extremely mindful of possible outliers and their adverse effects during any attempt to measure the relationship between two continuous variables. This is particularly true when using methods that rely on the mean of a given variable, as is the case in both correlation and regression analysis. You should recall from an earlier chapter that <strong>means</strong> are extremely sensitive to outliers, whether positively or negatively skewed. Therefore, let’s take a quick look at how our two variables <code>w1_h_expenditure</code> and <code>w1_hhincome</code> are distributed. Note, it is always a good idea to get a feel for the variables you are using, before jumping into statistical analyses. One simple way to accomplish this is to graph these variables in one scatter plot. Let’s try it:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(scales)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;scales&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     discard</code></pre>
<pre><code>## The following object is masked from &#39;package:readr&#39;:
## 
##     col_factor</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nids<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(hhrestrict<span class="op">==</span><span class="dv">1</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(w1_h_expenditure, w1_hhincome)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(., <span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Household monthly income - full imputations&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Household Expenditure with full imputations&quot;</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<pre><code>## Adding missing grouping variables: `hhid`</code></pre>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Now, it appears that there is a positive relationship between the two variables as the points with higher income levels tend to also have higher expenditure values. However, a large proportion of the points are concentrated in the lower left-hand corner of the graph and it is very difficult to see what is going on there. It may be the case that the positive relationship is only exhibited by households with high income and expenditure values. In order to get a better idea, we can ask R to include a fitted line which might provide us with a better indication of the relationship between the two variables. The <code>stat_smooth</code> function helps us to fit the line as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nids<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(hhrestrict<span class="op">==</span><span class="dv">1</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(w1_h_expenditure, w1_hhincome)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(., <span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Household monthly income - full imputations&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Household Expenditure with full imputations&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<pre><code>## Adding missing grouping variables: `hhid`</code></pre>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>We see here that the fitted line is upward sloping which supports our initial conclusion of a positive relationship between expenditure and income. Further, it is informative to think about exactly how R draws a fitted line. Basically it tries to find the straight line that minimizes the ‘distance’ between the all points and the fitted line. Exactly how it does this is beyond the scope of this course. However, the point is that this is essentially a pictorial representation of what a simple linear regression does. It finds the best fit straight line to reflect the relationship between two variables. However, regression analysis is much richer and can give us far more information than just the parameters of the straight line. More on that below, but first let us complete our brief look at outliers by seeing what happens to the straight line when we remove the two outliers circled in red below:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">scatter&lt;-nids<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(hhrestrict<span class="op">==</span><span class="dv">1</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(w1_h_expenditure, w1_hhincome)</code></pre></div>
<pre><code>## Adding missing grouping variables: `hhid`</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(scatter, <span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Household monthly income - full imputations&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Household Expenditure with full imputations&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> <span class="kw">subset</span>(scatter, w1_h_expenditure <span class="op">&gt;</span><span class="st"> </span><span class="dv">130000</span>), <span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure), <span class="dt">colour=</span><span class="st">&quot;red&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">data =</span> <span class="kw">subset</span>(scatter, w1_h_expenditure <span class="op">&lt;</span><span class="st"> </span><span class="dv">130000</span>), <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;green&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>A more elegant way of highlighting points using <code>ggalt</code> <span class="citation">(Rudis, Bolker, and Schulz <a href="#ref-R-ggalt">2017</a>)</span> <code>geom_encircle</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggalt)
<span class="kw">ggplot</span>(scatter, <span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Household monthly income - full imputations&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Household Expenditure with full imputations&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">data =</span> scatter <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(w1_h_expenditure <span class="op">&lt;</span><span class="st"> </span><span class="dv">130000</span>), <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;green&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_encircle</span>(<span class="dt">data =</span> scatter <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(w1_h_expenditure <span class="op">&gt;</span><span class="st"> </span><span class="dv">130000</span>),
                <span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure), 
                <span class="dt">color=</span><span class="st">&quot;red&quot;</span>, 
                <span class="dt">size=</span><span class="dv">2</span>, 
                <span class="dt">expand=</span><span class="fl">0.01</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>These two circled households are spending FAR more than their income. This in itself is not a contradiction as it is possible that they are spending wealth that was accumulated in the past or through inheritance. Here, it is simply informative to see how much of an influence they exert on our fitted line, regardless of whether they are valid expenditure values. The green line indicates the fitted line without their influence and while it may seem close to the red line, there is a marked difference considering that we have only excluded 2 out of 7305 observations. We will see below that slope of the red line is 0.615, while the slope of the green line is 0.593. If we interpret these results, we would say in the first case that for every extra rand of income the average household will spend 61.5 cents more. In the second case, they will spend 59.3 cents more. This becomes a sizable difference if we talk about increasing a household’s income by R5000: The first case will predict a R3075 increase in expenditure, while the second case will predict only a R2965 increase in expenditure. This again illustrates the large effect that outliers can have.</p>
<p>A point of caution: You should be extremely wary of deleting data (e.g. in the case of outliers). You must always make sure you have strong reasons for doing so and are not simply doing so because it will give you ‘nice’ results! For instance, here deleting these two circled observations because the households’ expenditures exceed their incomes would be unjustified as many of the other households also spend more than their income (see the graph below).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">scatter&lt;-scatter <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">spend=</span><span class="kw">ifelse</span>(w1_h_expenditure <span class="op">&lt;</span><span class="st"> </span>w1_hhincome,<span class="dv">1</span>,<span class="dv">2</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">spend=</span><span class="kw">factor</span>(spend, <span class="dt">levels=</span><span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,<span class="dt">labels=</span><span class="kw">c</span>(<span class="st">&quot;expend&lt;income&quot;</span>, <span class="st">&quot;expend&gt;income&quot;</span>))) 

  <span class="kw">ggplot</span>(scatter, <span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure, <span class="dt">color=</span>spend)) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_color_manual</span>(<span class="dt">values=</span><span class="kw">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;green&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">stat_smooth</span>(<span class="dt">data =</span> <span class="kw">subset</span>(scatter, w1_h_expenditure <span class="op">&lt;</span><span class="st"> </span>w1_hhincome), <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;orange&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">    </span><span class="kw">xlab</span>(<span class="st">&quot;Household monthly income&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Household Expenditure&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme_classic</span>()</code></pre></div>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>All the blue dots represent households that have a higher expenditure than income. The orange line is the fitted line that we would get if we excluded all of these values. While it may be the case that some of the blue dots are errors, it is highly unlikely that all of them are. Therefore, we would have been unjustified in deleting the two outliers we initially identified simply because their expenditure exceeded their income. The general message is that while outliers can influence your results substantially, you need to be VERY careful in how you deal with them! Also, take the time to get well acquainted with your data!</p>
<p><strong>Formally Testing for Outliers</strong></p>
<p>There is some disagreement in the field regarding the handling of outliers. Some fields in social research suggest and embrace an active approach to the handling of outliers, whereas others take a more hands-off approach. Neither one approach is superior to the other; after all, both are efforts to minimize the effects of extreme values. On one hand, the aggressive approach chooses to control for the ill effects by eliminating cases from the models. Whereas the handsoff approach, often chooses to use more robust estimation procedures which can handle extreme values in the data.</p>
<p>For our purposes, we do not eliminate any observations from our data for 3 reasons: 1) we do not have a serious outlier problem, 2) an in depth study of how to formally handle outliers is beyond the scope of this course, and 3) we advocate the use of more robust procedures to handle possible outliers, however, those procedures are also beyond the scope of this course.</p>
</div>
<div id="simple-regression" class="section level2">
<h2><span class="header-section-number">7.5</span> Simple regression</h2>
<p>Now that we have reviewed the issue of outliers, we can proceed with our study of regression using R.</p>
<p>Simple OLS regression (Ordinary Least Square regression) is a procedure that determines the best fitting regression line between two variables. In essence, the OLS regression line reduces the sum of squared errors to a minimum between two variables. We saw a graphical representation of this when we used R to construct fitted straight lines. It is beyond the scope of this course to teach you the finer points and intricacies of regression analysis; however, we will provide useful examples to give you a feel for what it is in general. Our main purpose here will be to show you how to use R to calculate the regression line between two variables and how to interpret the results. If you are not clear on what exactly regression is or would like to have a deeper understanding of it, we suggest that you take a course in statistics relating to your field of interest.</p>
<p>In general, the simplest relationship between an independent and dependent variable can be expressed in the linear formula,</p>
<p><span class="math inline">\(Y = \alpha + \beta X\)</span></p>
<p>where <strong>Y</strong> is the dependent variable and <strong>X</strong> is the independent variable. This is just the same formula that you used in school for defining a straight line. The coefficient “<span class="math inline">\(\beta\)</span>” is referred to as the slope and tells us how a 1 unit change in <strong>X</strong> will change the value of <strong>Y</strong>. The coefficient “<span class="math inline">\(\alpha\)</span>”&quot; tells us the value of <strong>Y</strong> when the independent variable <strong>X</strong> is zero. On an <strong>X</strong>-by-<strong>Y</strong> graph, the coefficient “<span class="math inline">\(\alpha\)</span>” is where the regression line intercepts with the y-axis.</p>
<p>In the case of <code>w1_hhincome</code> and <code>w1_h_expenditure</code>, the equation can be written as follows:</p>
<p><span class="math inline">\(w1\_h\_expenditure = \alpha + \beta* w1\_hhincome\)</span></p>
<p>This equation states that if you increase total monthly household income by one unit there will be a corresponding change (<span class="math inline">\(\beta\)</span>) in total monthly household expenditure.</p>
<p>Remember that we can type <code>help()</code> and the command of interest to learn more about that command R. If we type <code>help(lm)</code> we will get a full description of the regression command, its options and its syntax. For our purposes we can type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm0 &lt;-<span class="st"> </span><span class="kw">lm</span>(w1_h_expenditure <span class="op">~</span><span class="st"> </span>w1_hhincome, <span class="dt">data =</span> nids <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(hhrestrict<span class="op">==</span><span class="dv">1</span>))</code></pre></div>
<p>To see full results, we can use the summary function as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#anova(lm0)</span>
<span class="kw">summary</span>(lm0)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = w1_h_expenditure ~ w1_hhincome, data = nids %&gt;% 
##     filter(hhrestrict == 1))
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -60739  -1231   -758     53 108202 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.115e+03  6.954e+01   16.03   &lt;2e-16 ***
## w1_hhincome 6.146e-01  7.558e-03   81.31   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5194 on 7303 degrees of freedom
## Multiple R-squared:  0.4752, Adjusted R-squared:  0.4751 
## F-statistic:  6612 on 1 and 7303 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>To get the coefficients:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(lm0)<span class="op">$</span>coefficients</code></pre></div>
<pre><code>##                 Estimate   Std. Error  t value     Pr(&gt;|t|)
## (Intercept) 1115.0143048 69.544789721 16.03304 6.969086e-57
## w1_hhincome    0.6145542  0.007557776 81.31416 0.000000e+00</code></pre>
<p>You might also want to check the following functions and many more regression related output:</p>
<p><code>attributes(lm0)</code></p>
<p><code>attributes(summary(lm0))</code></p>
</div>
<div id="understanding-regression-output-tables" class="section level2">
<h2><span class="header-section-number">7.6</span> Understanding regression output tables</h2>
<p>What do all these numbers mean? By way of comparison, Stata produces the analysis of variance (ANOVA) table by default and this can be obtained in R by typing <code>anova(lm0)</code>. Although we are not particularly interested in this portion of the results, you can learn more about it, if interested click <a href="simple-regression-analysis.html#appendix-a-analysis-of-variance-anova-table">here</a>.</p>
<p>For the purposes of understanding the basic relationship between <code>w1_h_expenditure</code> and <code>w1_hhincome</code>, we will focus on three pieces of information provided by the output above. First, let’s recall the basic linear regression equation:</p>
<p><span class="math inline">\(Y = a + bX\)</span> or in our case: <span class="math inline">\(w1\_h\_expenditure = \alpha + \beta *w1\_hhincome\)</span></p>
<p>If we look at the regression output coefficients above, we can find the relevant estimates of the parameters ‘a’ and ‘b’ in the ‘Estiamte’ column of the <code>summary(lm0)$coefficients</code> output table. The <code>(Intercept)</code> is our estimated value for ‘a’ and the coefficient corresponding to <code>w1_hhincome</code> is the estimate for ‘b’. If we plug these results into their appropriate spot in the equation, we get:</p>
<p><strong>(predicted w1_h_expenditure) = 1115.014 + 0.6145542 x (w1_hhincome)</strong></p>
<p>In words, this equation is telling us that for every one rand increase in total monthly household income (<code>w1_hhincome</code>), total monthly household expenditure (<code>w1_h_expenditure</code>) will increase by almost 0.615 Rand (in other words, on average 61.5% of household income goes into household expenditure). The regression output also gives us a t-value and associated probability value for each coefficient. Here, the t-value of 81.31 and associated <code>Pr(&gt;|t|)</code>-value of 0 the income coefficient is statistically significant. Or in other words, that the probability that it is equal to zero is less than 0.1 percent.</p>
<p>If we turn our attention to our estimated value of ‘a’, the constant (<code>(Intercept)</code>) tells us that when our independent variable w1_hhincome equals zero, w1_h_expenditure is R1 115.01. This would suggest that when a household has no income its expenditure will be R1 1150.01. We might view this as a crude measure of the minimum necessary expenditure of a household.</p>
<p>Another important piece of information is the R-squared (<code>Multiple R-squared</code>) at the bottom of the <code>summary</code> output which equals 0.475. In essence, this value tells us that by knowing the value of our independent variable (<code>w1_hhincome</code>) we can estimate the value of the dependent variable (<code>w1_h_expenditure</code>) approximately 47.5% better than by simply guessing the mean. Or as more commonly talked about, we can account for about 47.5% of the variation around the mean of <code>w1_h_expenditure</code> with the knowledge of <code>w1_hhincome</code>. If you are interested in knowing what some of the other output means, click <a href="simple-regression-analysis.html#appendix-b-further-understanding-the-regression-results-table">here</a></p>
<p><strong>The Case of Simple Regression</strong></p>
<p>Now that we have a formula which relates a household’s income to its expenditure, if someone we are told what a household’s total income is, we can use our formula to predict what its expenditure might be. I’m sure you can see that there will be cases in which this prediction is extremely far off. Nevertheless, it is better than a pure guess. Our regression output also told us that income only explains 47.5% of the variation in expenditure, so we are not claiming to make perfect predictions. In the next chapter, we will look at how we can improve our regression predictions by adding extra relevant variables.</p>
<p>But for now, let’s see how well we can predict expenditure of households, simply by using our equation and the level of income that each household has. Let’s say that we come across a South African household that has a total monthly income of R5000 and we want to know roughly how much they are likely to spend each month. Using our formula, we plug in 5000 in place of X and then calculate Y:</p>
<p>Y = a + b<span class="math inline">\(*\)</span>X gives Y = 1115.014 + 0.6145542$*$5000</p>
<p>Now, you can simply type the following in R’s console to evaluate the right-hand side of this equation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">1115.014</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.6145542</span><span class="op">*</span><span class="dv">5000</span></code></pre></div>
<pre><code>## [1] 4187.785</code></pre>
<p>This tells us that the average household that has an income of R5 000 will have a total household expenditure of R4 187.79. It is important to realize that a regression equation will almost never fit the actual observed values perfectly. Therefore, the estimated value of monthly expenditure that our calculation predicts (4 187.79) is just that, a prediction.</p>
<p>We can look at how well our equation predicts the expenditure values for the real households in our sample. We do this by creating a new variable that takes each household’s income and uses it to predict how that household’s expenditure. We can then compare the predicted expenditure values with the actual expenditure values of the households in the sample. Let’s do this.</p>
<p>R calculates predicted values (<code>fitted.values</code>) and residuals (<code>residuals</code>) automatically (compared to Stata). You can check other attributes of an <code>lm</code> by typing (for the previous model):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attributes</span>(lm0)</code></pre></div>
<pre><code>## $names
##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;        
## 
## $class
## [1] &quot;lm&quot;</code></pre>
<p>We just need to bring in these fitted values to the data frame, they are in the same order of the data that generated the model if we have not rearranged the data.</p>
<p>We are going to create a cleaner subset of the data (<code>nids2</code>) and run the model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nids2&lt;-<span class="kw">subset</span>(nids,<span class="dt">subset=</span>hhrestrict<span class="op">==</span><span class="dv">1</span>, <span class="dt">select=</span><span class="kw">c</span>(hhid, w1_hhincome,w1_h_expenditure))
lm0 &lt;-<span class="st"> </span><span class="kw">lm</span>(w1_h_expenditure <span class="op">~</span><span class="st"> </span>w1_hhincome, <span class="dt">data =</span> nids2)
nids2<span class="op">$</span>yhat&lt;-lm0<span class="op">$</span>fitted.values</code></pre></div>
<p>Let’s compare our new estimated variable with the actual household expenditure values:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(nids2, <span class="dt">n=</span>20L)</code></pre></div>
<pre><code>## # A tibble: 20 x 4
## # Groups:   hhid [20]
##      hhid w1_hhincome w1_h_expenditure  yhat
##     &lt;int&gt;       &lt;dbl&gt;            &lt;dbl&gt; &lt;dbl&gt;
##  1 101012       1045.             518. 1757.
##  2 101013        588.             861. 1477.
##  3 101014       1307.             614. 1918.
##  4 101015        291.             369. 1294.
##  5 101016       1304.            1259. 1916.
##  6 101017        213.             483. 1246.
##  7 101018       1785.            1464. 2212.
##  8 101020       1831.            1023. 2241.
##  9 101021       1235.            1426. 1874.
## 10 101022       2489             2581  2645.
## 11 101023       2745.            1280. 2802.
## 12 101024        309.            1494. 1305.
## 13 101025       1087.            1456. 1783.
## 14 101027       1268.            2080. 1894.
## 15 101028       1128.            1351. 1808.
## 16 101029       1096.            1717. 1789.
## 17 101030       1608.            1487. 2103.
## 18 101033        815.            1495. 1616.
## 19 101034       2040             1903. 2369.
## 20 101035        996.             826. 1727.</code></pre>
<p>Here is a partial view of what the resulting table should look like:</p>
<p>The third column gives the actual expenditure values, the fourth gives the predicted expenditure values and the second gives the actual income levels used in our prediction. Comparing columns 3 and 4, it is immediately clear that the predicted values are quite far off the actual values. You may also notice that the predicted values tend to be substantially larger than the actual values and often the predicted values are higher than the income level of the household. If we look back at our prediction equation, we see that this is due to the large ‘a’ value of R1 115.01. This means that anyone earning less than R3145.30 will have a predicted expenditure greater than their income. As we saw above, a large proportion of the sample households do have higher reported expenditures than income. Nevertheless, it appears that the predicted values are too high. This is due to the fact that by running a regression, we are forcing a straight line relationship between income and expenditure and therefore households with extremely high income levels might be pulling the estimated ‘a’ value far higher than it should be.</p>
<p>This serves to illustrate that it is always good to examine your results critically. For instance, after running the regression above, you should ask yourself whether it makes sense that a household with an income level of R0 will on average spend R1 115.01. And if not, you should try to figure out what is causing the result to be biased. We will not go further in investigating this, but you might want to check whether you can get better estimates if you exclude individuals with high income levels. It might be the case that the relationship between income and expenditure is different for rich and poor people.</p>
<p>While our expenditure predictions are not great, it is worth realizing that they are still better than just guessing R3777.12 for each household, the sample mean for <code>w1_h_expenditure</code>.</p>
<p>BUT, is this the best we can do? In the next chapter, we will see how by adding more information to our regression, we may be able to improve our predictions. What other variables do you think might influence a household’s expenditure?</p>
<p>For now, let’s practice some simple regressions to make sure we are comfortable with what we have learnt.</p>
<p><strong>2. By how much would you expect a household to increase its total monthly food expenditure for every additional household member?</strong></p>
<p>Question 2 Answer</p>
<p><strong>3. Income also affects households’ total monthly food expenditure. Try a simple regression of w1_h_expf on total monthly income. Write an equation for this relationship and interpret the result.</strong></p>
<p>Question 3 Answer</p>
</div>
<div id="graphing-the-regression-equation" class="section level2">
<h2><span class="header-section-number">7.7</span> Graphing the regression equation</h2>
<p>Having obtained the predicted values of the dependent variable <code>w1_h_expenditure</code>, we can plot them against income using a scatter plot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(nids2, <span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> yhat)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> yhat), <span class="dt">colour=</span><span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">80000</span>,<span class="dv">20000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Household monthly income&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Predicted household expenditure&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>This shows us how R is essentially forcing a straight line relationship between the two variables when we run an ordinary linear regression as we did above. We can also see how the observations are much denser at lower income levels. It may be informative for us to add the scatterplot of the actual income and actual expenditure values, and also to add in the fitted line to cement the basic idea of what a regression is doing.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(nids2, <span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, <span class="dt">y =</span> w1_h_expenditure), <span class="dt">colour=</span><span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> w1_hhincome, yhat), <span class="dt">colour=</span><span class="st">&quot;green&quot;</span>, <span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">150000</span>,<span class="dv">50000</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Household monthly income - full imputations&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Expenditure (Actual &amp; Predicted)&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Here, green dots are the scatterpoints from the graph directly above - i.e. the scatter of <code>yhat</code> against household monthly income. And we saw the blue scatterplot and red line towards the beginning of this chapter when we discussed outliers. We can see that all the scatterpoints fall directly on the fitted line. Notice, the scatterpoints come from the predicted values that we obtained from our regression, while the fitted line is constructed by R simply using the original data and finding the best fitted line. This graph clearly illustrates the idea that what a regression is doing is finding the best-fit straight line and then estimating the slope and intercept of this line. As we saw above, it also provides us with a range of further useful information.</p>
<p>We asked earlier whether this is the best we can do in terms of predicting household expenditure or whether you could think of any other variables that might influence a household’s expenditure level. In answer to the first question, it is not! How about the number of household members? Surely, a household with 10 members will spend more than a household with 1 - even if they have the same level of income. How about whether the household is in a rural versus a metropolitan setting? If we could incorporate the information contained in these extra variables then it is likely that we will be able to better understand the determinants of household spending. While, to a large extent we have focused in this chapter on using the parameters that we calculate using regression to obtain predicted values of expenditure, prediction is more of a byproduct of regression analysis, not its primary aim. Regression analysis is more generally used to understand and quantify the relationship between a set of variables. With regards to our expenditure example, this will take the form of trying to understand what factors influence household spending and by how much does each factor effect household spending. This information can then be used in various different ways, depending on your research question - one of these is to predict what would happen to household expenditure if we varied one or more of the dependent variables.</p>
<p>This type of analysis, however, requires more than a simple regression between two variables, it requires what is known as multiple regression. We cover multiple regression in the next chapter. But first, let’s work through an interesting worked example which looks at the relationship between a person’s body index and her age. What are your expectations about this relationship?</p>
</div>
<div id="worked-example-is-age-a-strong-determinant-of-bmi" class="section level2">
<h2><span class="header-section-number">7.8</span> Worked example: Is age a strong determinant of BMI?</h2>
<p>In chapter 5, we began investigating the relationship between BMI and age. Recall that BMI is derived from weight and height. Since height does not change substantially in adulthood, adult BMI changes as a result of changes in weight. Think about how a person’s weight changes over their adult life cycle. As a result of this, what would you expect the relationship between BMI and age to be?</p>
<p>You are probably beginning to realize that when analyzing a relationship between variables it is useful to start with a hypothesis or set of hypotheses and then interrogate them. During this process we reject the hypotheses found to be false and accept or update the others.</p>
<p>What is your hypothesis about the relationship between BMI and age? Do you think it will be a linear or non-linear relationship? Would you expect this relationship to be different for men and women?</p>
<p>We restrict the BMI value to exclude people with extreme BMI values and check the correlation between BMI and age. Note, that we also created a new variable called <code>‘adult_age’</code> in the “getting ready” section at the beginning of the chapter. This variable is essentially exactly the same as the <code>w1_a_best_age_yrs</code> variable except that it has no negative values and has a slightly less cumbersome name.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">corr2.df&lt;-nids[nids<span class="op">$</span>bmi_valid<span class="op">==</span><span class="dv">1</span>,<span class="kw">c</span>(<span class="st">&quot;bmi&quot;</span>,<span class="st">&quot;age_adult&quot;</span>)]
<span class="kw">cor</span>(corr2.df,<span class="dt">use=</span><span class="st">&quot;complete.obs&quot;</span>)</code></pre></div>
<pre><code>##                 bmi age_adult
## bmi       1.0000000 0.1465733
## age_adult 0.1465733 1.0000000</code></pre>
<p>BMI and age are positively correlated. The correlation between BMI and age is much lower than the correlation found between expenditure and income seen previously in this chapter. Why do you think this is? Does this mean that BMI is not related to age?</p>
<p>A simple scatterplot gives us the relationship between BMI and age over different values of BMI and age.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(corr2.df, <span class="kw">aes</span>(<span class="dt">x =</span> age_adult, <span class="dt">y =</span> bmi)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age_adult, <span class="dt">y =</span> bmi), <span class="dt">colour=</span><span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;gam&quot;</span>, <span class="dt">formula=</span> y <span class="op">~</span><span class="st"> </span><span class="kw">s</span>(x, <span class="dt">k =</span> <span class="dv">3</span>), <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">colour =</span> <span class="st">&quot;green&quot;</span>, <span class="kw">aes</span>(<span class="dt">colour =</span> <span class="st">&quot;polynomial&quot;</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">20</span>,<span class="dv">100</span>,<span class="dv">20</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">10</span>,<span class="dv">50</span>,<span class="dv">10</span>), <span class="dt">labels =</span> comma) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;age in years - adults&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;BMI&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<pre><code>## Warning: Removed 20536 rows containing non-finite values (stat_smooth).

## Warning: Removed 20536 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 20536 rows containing missing values (geom_point).</code></pre>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Observing the scatter, the relationship between BMI and age looks tenuous. However, the trend lines suggest that there is a nonlinear relationship between BMI and age; BMI increases with age until around age 50 and decreases thereafter. This means that adult’s weight tends to increase until they are around 50 and thereafter starts to decrease. Does this make sense? Let’s investigate this nonlinear trend.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bmi_age_df&lt;-corr2.df<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(age_adult)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">bmi_age =</span> <span class="kw">mean</span>(bmi, <span class="dt">na.rm =</span> T)) <span class="co">#use mutate if you want to generate a new var as opposed to summarising</span></code></pre></div>
<p>This code assigns the mean BMI for individuals of a given age to each individual of that age. For example, if there are only 3 people of age 30 in the sample with BMI values of 20, 22 and 27, then they will all get assigned a bmi_age value of 23 (the mean of the three BMI values). To see the mean bmi by age, browse the following.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(bmi_age_df, <span class="dt">n=</span>20L)</code></pre></div>
<pre><code>## # A tibble: 20 x 2
##    age_adult bmi_age
##        &lt;int&gt;   &lt;dbl&gt;
##  1        21    24.3
##  2        22    24.0
##  3        23    24.5
##  4        24    24.7
##  5        25    24.5
##  6        26    24.9
##  7        27    25.4
##  8        28    25.5
##  9        29    26.0
## 10        30    24.9
## 11        31    26.0
## 12        32    25.7
## 13        33    26.9
## 14        34    26.3
## 15        35    27.4
## 16        36    26.8
## 17        37    28.1
## 18        38    27.9
## 19        39    28.3
## 20        40    27.5</code></pre>
<p>You can then see that all the 21 year olds in the sample were assigned a <code>bmi_age</code> value of 24.3. On average, 21 year olds in our sample have a BMI of 24.3. It will be much more interesting to see how this average <code>bmi_age</code> variable changes with age.</p>
<p>We can investigate this by plotting the mean bmi by age variable against age.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(bmi_age_df, <span class="kw">aes</span>(<span class="dt">x =</span> age_adult, <span class="dt">y =</span> bmi_age)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age_adult, <span class="dt">y =</span> bmi_age), <span class="dt">colour=</span><span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Age&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Mean BMI (by age_adult)&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>The nonlinear relationship between BMI and ages emerges clearly. BMI increases sharply with age between 20 and 40 years of age, stays relatively stable through the middle ages and then becomes more erratic at older ages, with a general downward trend. If your hypothesis about the relationship between BMI and age was that BMI increases with age up until 60 and thereafter declines, the scatterplot supports your hypothesis. Part of the reason the relationship is less stable at older ages is that there are fewer individuals in these older groups.</p>
<p>The relationship between BMI and age might be different for men and women. How would you go about investigating this?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nids<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(age_bins, gender)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Mean =</span> <span class="kw">mean</span>(bmi, <span class="dt">na.rm=</span><span class="ot">TRUE</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">na.omit</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">arrange</span>(gender, age_bins)</code></pre></div>
<pre><code>## # A tibble: 12 x 3
## # Groups:   age_bins [6]
##    age_bins     gender  Mean
##    &lt;fct&gt;        &lt;fct&gt;  &lt;dbl&gt;
##  1 20 - 29 yrs  Male    22.7
##  2 30 - 39 yrs  Male    23.7
##  3 40 - 49 yrs  Male    24.2
##  4 50 - 59 yrs  Male    25.5
##  5 60 - 69 yrs  Male    25.0
##  6 70 - 120 yrs Male    25.0
##  7 20 - 29 yrs  Female  26.8
##  8 30 - 39 yrs  Female  29.4
##  9 40 - 49 yrs  Female  30.5
## 10 50 - 59 yrs  Female  30.1
## 11 60 - 69 yrs  Female  30.4
## 12 70 - 120 yrs Female  29.0</code></pre>
<p>The table suggests that the quadratic relationship between BMI and age is slightly stronger for females than males. Female mean BMI increases substantially between the 20s and 30s, increases a little further between the 30s and 40s, then remains fairly stable between the 40s and 60s and decreases thereafter. Male BMI increases more steadily until the 50s and decreases marginally thereafter. Is this supported when we use the correlation command?</p>
<p><strong>• Females: Below 60 years old</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fb60&lt;-nids[nids<span class="op">$</span>bmi_valid<span class="op">==</span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>age_adult <span class="op">&lt;</span><span class="st"> </span><span class="dv">60</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_a_b2 <span class="op">==</span><span class="st"> </span><span class="dv">2</span>,<span class="kw">c</span>(<span class="st">&quot;bmi&quot;</span>,<span class="st">&quot;age_adult&quot;</span>)]
<span class="kw">cor</span>(fb60, <span class="dt">use=</span><span class="st">&quot;complete.obs&quot;</span>)</code></pre></div>
<pre><code>##                 bmi age_adult
## bmi       1.0000000 0.2135916
## age_adult 0.2135916 1.0000000</code></pre>
<p><strong>• Females: Over 60 years old</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fo60&lt;-nids[nids<span class="op">$</span>bmi_valid<span class="op">==</span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>age_adult <span class="op">&gt;</span><span class="st"> </span><span class="dv">60</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_a_b2 <span class="op">==</span><span class="st"> </span><span class="dv">2</span>,<span class="kw">c</span>(<span class="st">&quot;bmi&quot;</span>,<span class="st">&quot;age_adult&quot;</span>)]
<span class="kw">cor</span>(fo60, <span class="dt">use=</span><span class="st">&quot;complete.obs&quot;</span>)</code></pre></div>
<pre><code>##                  bmi  age_adult
## bmi        1.0000000 -0.1449253
## age_adult -0.1449253  1.0000000</code></pre>
<p><strong>• Males: Below 60 years old</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mb60&lt;-nids[nids<span class="op">$</span>bmi_valid<span class="op">==</span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>age_adult <span class="op">&lt;</span><span class="st"> </span><span class="dv">60</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_a_b2 <span class="op">==</span><span class="st"> </span><span class="dv">1</span>,<span class="kw">c</span>(<span class="st">&quot;bmi&quot;</span>,<span class="st">&quot;age_adult&quot;</span>)]
<span class="kw">cor</span>(mb60, <span class="dt">use=</span><span class="st">&quot;complete.obs&quot;</span>)</code></pre></div>
<pre><code>##                 bmi age_adult
## bmi       1.0000000 0.1897421
## age_adult 0.1897421 1.0000000</code></pre>
<p><strong>• Males: Over 60 years old</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mo60&lt;-nids[nids<span class="op">$</span>bmi_valid<span class="op">==</span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>age_adult <span class="op">&gt;</span><span class="st"> </span><span class="dv">60</span> <span class="op">&amp;</span><span class="st"> </span>nids<span class="op">$</span>w1_a_b2 <span class="op">==</span><span class="st"> </span><span class="dv">1</span>,<span class="kw">c</span>(<span class="st">&quot;bmi&quot;</span>,<span class="st">&quot;age_adult&quot;</span>)]
<span class="kw">cor</span>(mo60, <span class="dt">use=</span><span class="st">&quot;complete.obs&quot;</span>)</code></pre></div>
<pre><code>##                   bmi   age_adult
## bmi        1.00000000 -0.08561469
## age_adult -0.08561469  1.00000000</code></pre>
<p>Alternatively, in one pipe:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nids <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(bmi_valid<span class="op">==</span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(bmi,age_adult, gender) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_adult_2=</span><span class="kw">ifelse</span>(age_adult <span class="op">&lt;</span><span class="st"> </span><span class="dv">60</span>,<span class="dv">1</span>,<span class="dv">2</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_adult_2=</span><span class="kw">factor</span>(age_adult_<span class="dv">2</span>, <span class="dt">labels=</span><span class="kw">c</span>(<span class="st">&quot;Under 60&quot;</span>, <span class="st">&quot;Over 60&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(age_adult_<span class="dv">2</span>,gender) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">corr=</span><span class="kw">cor</span>(bmi, age_adult))</code></pre></div>
<pre><code>## Adding missing grouping variables: `hhid`</code></pre>
<pre><code>## # A tibble: 4 x 3
## # Groups:   age_adult_2 [?]
##   age_adult_2 gender    corr
##   &lt;fct&gt;       &lt;fct&gt;    &lt;dbl&gt;
## 1 Under 60    Male    0.190 
## 2 Under 60    Female  0.214 
## 3 Over 60     Male   -0.0697
## 4 Over 60     Female -0.145</code></pre>
<p>What do these results tell us? They seem to further support the idea that the relationship between BMI and age is positive for younger adults and negative over the age of 60. They also suggest that relationship between age and BMI is stronger for women than men on both the positive and negative sections of the parabolic relationship.</p>
<p>We now have a fairly good idea of the general relationship between BMI and age. To gain a more precise understanding of this relationship we use regression. Regression allows us to quantify the relationship between the two variables. How large is the influence of age on BMI?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm1 &lt;-<span class="st"> </span><span class="kw">lm</span>(bmi<span class="op">~</span>age_adult, <span class="dt">data =</span> <span class="kw">subset</span>(nids,<span class="dt">subset=</span>bmi_valid<span class="op">==</span><span class="dv">1</span>, <span class="dt">select=</span><span class="kw">c</span>(bmi,age_adult)))
<span class="kw">summary</span>(lm1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bmi ~ age_adult, data = subset(nids, subset = bmi_valid == 
##     1, select = c(bmi, age_adult)))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -14.680  -4.791  -1.172   3.899  24.372 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.160418   0.180727  133.69   &lt;2e-16 ***
## age_adult    0.060722   0.003974   15.28   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.554 on 10632 degrees of freedom
## Multiple R-squared:  0.02148,    Adjusted R-squared:  0.02139 
## F-statistic: 233.4 on 1 and 10632 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>What does this tell us? On average, a one year increase in age is associated with a 0.06 unit increase in BMI.</p>
<p>You will notice that the R-squared value is far lower than the one from the regression of expenditure on income. Why do you think this is? The relationship between expenditure and income is well defined - the more you have, the more you can spend. In general, relationships between variables are more complex. A low R-squared value just says that age only explains a small part of the variation in BMI values. Alternatively, it might be reflecting the fact that by running a regression we are assuming a linear relationship. As we have seen above, it is likely that the relationship is in fact non-linear.</p>
<p>Even if we only look at 21 - 40 year olds where we might expect a linear relationship between BMI and age, it is to be expected that age would only explain a relatively small part of the variation in BMI, as we showed that BMI varied between genders, as well as between racial and income groups and we have not accounted for these characteristics. Besides these factors, can you think of other factors that would explain variation in BMI? How about genetics? Education? Exercise? Quality of diet? We will only be able to account for these other factors when we move onto including multiple explanatory variables in our regressions in chapter 8.</p>
<p>Given what we have learnt from the summary measures about the relationship between BMI and age, is there any way we can improve on this regression? As we mentioned above, it is more appropriate to use regression where there is a linear relationship between the variables.</p>
<p>Therefore, we break our sample into three groups: between 20 and 40 years of age; between 40 and 60 years; and over 60 years. We then examine the relationship between BMI and age for each group.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm2 &lt;-<span class="st"> </span><span class="kw">lm</span>(bmi<span class="op">~</span>age_adult, <span class="dt">data =</span> <span class="kw">subset</span>(nids,<span class="dt">subset=</span>age_adult <span class="op">&lt;</span><span class="st"> </span><span class="dv">40</span> <span class="op">&amp;</span><span class="st"> </span>bmi_valid<span class="op">==</span><span class="dv">1</span>, <span class="dt">select=</span><span class="kw">c</span>(bmi,age_adult)))
lm3 &lt;-<span class="st"> </span><span class="kw">lm</span>(bmi<span class="op">~</span>age_adult, <span class="dt">data =</span> <span class="kw">subset</span>(nids,<span class="dt">subset=</span>age_adult <span class="op">&gt;=</span><span class="dv">40</span> <span class="op">&amp;</span><span class="st"> </span>age_adult <span class="op">&lt;</span><span class="dv">60</span> <span class="op">&amp;</span><span class="st"> </span>bmi_valid <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">select=</span><span class="kw">c</span>(bmi,age_adult)))
lm4 &lt;-<span class="st"> </span><span class="kw">lm</span>(bmi<span class="op">~</span>age_adult, <span class="dt">data =</span> <span class="kw">subset</span>(nids,<span class="dt">subset=</span>age_adult <span class="op">&gt;=</span><span class="st"> </span><span class="dv">60</span> <span class="op">&amp;</span><span class="st"> </span>bmi_valid <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">select=</span><span class="kw">c</span>(bmi,age_adult)))</code></pre></div>
<p>Using the R package,<code>stargazer</code> <span class="citation">(Hlavac <a href="#ref-R-stargazer">2018</a>)</span>, to present the regression models:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(stargazer)
<span class="kw">stargazer</span>(lm2,lm3,lm4, <span class="dt">type=</span><span class="st">&quot;text&quot;</span>, <span class="dt">model.numbers =</span> <span class="ot">FALSE</span>, <span class="dt">column.labels =</span> <span class="kw">c</span>(<span class="st">&quot;&lt;Under 40&quot;</span>,<span class="st">&quot;40-60&quot;</span>,<span class="st">&quot;Over 60&quot;</span>))</code></pre></div>
<pre><code>## 
## ==============================================================================================
##                                                Dependent variable:                            
##                     --------------------------------------------------------------------------
##                                                        bmi                                    
##                             &lt;Under 40                  40-60                  Over 60         
## ----------------------------------------------------------------------------------------------
## age_adult                   0.225***                 0.058***                -0.101***        
##                              (0.015)                  (0.020)                 (0.022)         
##                                                                                               
## Constant                    19.179***                25.003***               34.485***        
##                              (0.444)                  (0.999)                 (1.541)         
##                                                                                               
## ----------------------------------------------------------------------------------------------
## Observations                  5,199                    3,664                   1,771          
## R2                            0.042                    0.002                   0.012          
## Adjusted R2                   0.041                    0.002                   0.011          
## Residual Std. Error     6.029 (df = 5197)        6.953 (df = 3662)       6.742 (df = 1769)    
## F Statistic         225.338*** (df = 1; 5197) 8.205*** (df = 1; 3662) 20.916*** (df = 1; 1769)
## ==============================================================================================
## Note:                                                              *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p>Does restricting the age range of our sample affect the coefficient on age? Does it affect the constant? What is the interpretation of these two values and do they support the pattern that we saw in the graphs above?</p>
<p>The tabulation showed that the relationship between BMI and age is different for men and women. We saw that for each age group, the average female BMI was above the average male BMI. However, it is unclear from the table whether BMI increases and then decreases with age at the same rate for men and women. In other words, if you were to plot the relationship between BMI and age for men and women on the same graph, would they have the same slope?</p>
<p><strong>4. As a challenge, plot the relationship between BMI and age for men and women under 40 on the same graph. [Hint: Use a similar graph to one you plotted earlier in this chapter.]</strong></p>
<p>Question 4 Answer</p>
<p>The graph showed that the female trendline had a steeper slope than the male trendline. BMI increases at a faster rate with age for women than for men. Let’s use regression analysis to add number to the picture. How much faster does female BMI increase than male BMI between age 20 and 40.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm5 &lt;-<span class="st"> </span><span class="kw">lm</span>(bmi<span class="op">~</span>age_adult, <span class="dt">data =</span> <span class="kw">subset</span>(nids,<span class="dt">subset=</span>bmi_valid <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>age_adult <span class="op">&lt;</span><span class="st"> </span><span class="dv">40</span> <span class="op">&amp;</span><span class="st"> </span>w1_a_b2 <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">select=</span><span class="kw">c</span>(bmi,age_adult)))
<span class="kw">summary</span>(lm5)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bmi ~ age_adult, data = subset(nids, subset = bmi_valid == 
##     1 &amp; age_adult &lt; 40 &amp; w1_a_b2 == 1, select = c(bmi, age_adult)))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.7623 -3.0057 -0.7909  1.8930 25.7992 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 19.09161    0.52813  36.149  &lt; 2e-16 ***
## age_adult    0.13784    0.01788   7.709 1.96e-14 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.461 on 2062 degrees of freedom
## Multiple R-squared:  0.02801,    Adjusted R-squared:  0.02754 
## F-statistic: 59.42 on 1 and 2062 DF,  p-value: 1.965e-14</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm6 &lt;-<span class="st"> </span><span class="kw">lm</span>(bmi<span class="op">~</span>age_adult, <span class="dt">data =</span> <span class="kw">subset</span>(nids,<span class="dt">subset=</span>bmi_valid <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>age_adult <span class="op">&lt;</span><span class="st"> </span><span class="dv">40</span> <span class="op">&amp;</span><span class="st"> </span>w1_a_b2 <span class="op">==</span><span class="st"> </span><span class="dv">2</span>, <span class="dt">select=</span><span class="kw">c</span>(bmi,age_adult)))
<span class="kw">summary</span>(lm6)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bmi ~ age_adult, data = subset(nids, subset = bmi_valid == 
##     1 &amp; age_adult &lt; 40 &amp; w1_a_b2 == 2, select = c(bmi, age_adult)))
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.0241  -4.4192  -0.8955   3.7965  24.3588 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 19.55102    0.59101   33.08   &lt;2e-16 ***
## age_adult    0.27082    0.01989   13.62   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.288 on 3133 degrees of freedom
## Multiple R-squared:  0.05586,    Adjusted R-squared:  0.05556 
## F-statistic: 185.4 on 1 and 3133 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Does our regression output agree with the graph in question 4? What are the ‘slope’ coefficients of the two regressions? How do they compare to one another?</p>
<p>The age coefficients of the regressions clearly show that BMI increases with age substantially faster for women than for men between the ages of 20 and 40.</p>
<p>Now that you have had a decent introduction to running simple linear regressions in R, try your hand at the exercises to make sure that you have fully grasped the important concepts as you will need to be very familiar with the material in this chapter before you move on to chapter 8.</p>
</div>
<div id="question-answers-5" class="section level2">
<h2><span class="header-section-number">7.9</span> Question answers:</h2>
<p><strong>QUESTION 1 Answer</strong></p>
<p><strong>What is the correlation between the average household’s food expenditure and household size?</strong></p>
<p>Both household size, w1_hhsizer, and total monthly household food expenditure w1_h_expf, are household-level variables. Since we do not want to allow larger households to be weighted more heavily, let’s again use only one observation per household.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">q1&lt;-<span class="kw">data.frame</span>(<span class="kw">subset</span>(nids, <span class="dt">subset=</span>hhrestrict<span class="op">==</span><span class="dv">1</span>, <span class="dt">select=</span><span class="kw">c</span>(w1_hhsizer,w1_h_expf)))
<span class="kw">cor</span>(q1[,<span class="kw">c</span>(<span class="st">&quot;w1_hhsizer&quot;</span>,<span class="st">&quot;w1_h_expf&quot;</span>)],<span class="dt">use=</span><span class="st">&quot;complete.obs&quot;</span>)</code></pre></div>
<pre><code>##            w1_hhsizer w1_h_expf
## w1_hhsizer  1.0000000 0.1452078
## w1_h_expf   0.1452078 1.0000000</code></pre>
<p>From these results, we can conclude that there is a weak positive relationship between household size and expenditure on food. That is, larger households are somewhat more likely to spend more on food than smaller households. However, we cannot determine how much more without further analysis.</p>
<p><strong>QUESTION 2 ANSWER</strong></p>
<p><strong>By how much would you expect a household to increase its total monthly food expenditure for every additional household member?</strong></p>
<p>To figure this out, we need to use the following regress:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">q2 &lt;-<span class="st"> </span><span class="kw">lm</span>(w1_h_expf<span class="op">~</span>w1_hhsizer, <span class="dt">data =</span> <span class="kw">subset</span>(nids,<span class="dt">subset=</span>hhrestrict<span class="op">==</span><span class="dv">1</span>, <span class="dt">select=</span><span class="kw">c</span>(w1_hhsizer,w1_h_expf)))
<span class="kw">summary</span>(q2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = w1_h_expf ~ w1_hhsizer, data = subset(nids, subset = hhrestrict == 
##     1, select = c(w1_hhsizer, w1_h_expf)))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1209.1  -458.3  -238.3   179.6 13797.1 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  713.600     16.914   42.19   &lt;2e-16 ***
## w1_hhsizer    45.711      3.645   12.54   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 798.9 on 7303 degrees of freedom
## Multiple R-squared:  0.02109,    Adjusted R-squared:  0.02095 
## F-statistic: 157.3 on 1 and 7303 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This gives you a regression equation of:</p>
<p><span class="math inline">\((expfhat) = 713.600 + 45.711*(w1\_hhsizer)\)</span></p>
<p>Therefore, for every additional member, the average household can be expected to increase food expenditure by about R45.71 per month. If we tried to interpret the constant term here, we would want to say that if the household had no members expenditure on food would be 713.6 rand! This of course does not make much sense. We generally only interpret the constant when it makes sense to do so. Notice also that our model has significant F and T - values (Prob&gt;F = 0.0000 &amp; P&gt;|t|= 0.0000) although our R-squared value is very low; only 2% of the variation in monthly household food expenditure around its mean is explained by household size.</p>
<p><strong>QUESTION 3 ANSWER</strong></p>
<p><strong>Income also affects households’ total monthly food expenditure. Try a simple regression of w1_h_expf on total monthly household income. Write an equation for this relationship and interpret the result.</strong></p>
<p>Try the regression as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">q3 &lt;-<span class="st"> </span><span class="kw">lm</span>(w1_h_expf<span class="op">~</span>w1_hhincome, <span class="dt">data =</span> <span class="kw">subset</span>(nids,<span class="dt">subset=</span>hhrestrict<span class="op">==</span><span class="dv">1</span>, <span class="dt">select=</span><span class="kw">c</span>(w1_hhincome,w1_h_expf)))
<span class="kw">summary</span>(q3)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = w1_h_expf ~ w1_hhincome, data = subset(nids, subset = hhrestrict == 
##     1, select = c(w1_hhincome, w1_h_expf)))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6088.0  -354.3  -140.7   184.6  9687.9 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 6.323e+02  8.848e+00   71.46   &lt;2e-16 ***
## w1_hhincome 5.769e-02  9.616e-04   59.99   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 660.9 on 7303 degrees of freedom
## Multiple R-squared:  0.3301, Adjusted R-squared:   0.33 
## F-statistic:  3599 on 1 and 7303 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(q3)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = w1_h_expf ~ w1_hhincome, data = subset(nids, subset = hhrestrict == 
##     1, select = c(w1_hhincome, w1_h_expf)))
## 
## Coefficients:
## (Intercept)  w1_hhincome  
##   632.32020      0.05769</code></pre>
<p>The equation made by these coefficients equals:</p>
<p><span class="math inline">\((predicted w1\_h\_expf )= 632.3202 + .0576867*(w1\_hhincome)\)</span></p>
<p>For every R1000 increase in total monthly household income, monthly household food expenditure increases by approximately R58. Here we can interpret the coefficient of R632.32 as the mean monthly expenditure on food when a household has no income (i.e. the minimum food expenditure needed to survive). The R-squared value implies that the amount of variance of monthly household food expenditure explained by total monthly household income is 33%.</p>
<p><strong>QUESTION 4 - ANSWER</strong></p>
<p><strong>As a challenge plot the relationship between BMI and age for men and women under 40 on the same graph. [Hint: Use a similar graph to one you plotted earlier in this chapter.]</strong></p>
<p>You can copy the following (including the comments) into a do file to run:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bmiage&lt;-<span class="kw">subset</span>(nids, <span class="dt">subset=</span>(age_adult <span class="op">&gt;</span><span class="st"> </span><span class="dv">20</span> <span class="op">&amp;</span><span class="st"> </span>age_adult <span class="op">&lt;</span><span class="st"> </span><span class="dv">40</span>), <span class="dt">select=</span><span class="kw">c</span>(bmi, age_adult, gender))

<span class="co">#Generating a BMI variable giving mean BMI by age and gender to individuals of a common age-gender group </span>
bmiage&lt;-bmiage<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(age_adult, gender)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">bmi_age_gen=</span><span class="kw">mean</span>(bmi, <span class="dt">na.rm=</span><span class="ot">TRUE</span>))

<span class="kw">ggplot</span>(bmiage, <span class="kw">aes</span>(<span class="dt">x =</span> age_adult, <span class="dt">y =</span> bmi_age_gen, <span class="dt">group =</span> gender, <span class="dt">color =</span> gender)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span><span class="st">&quot;Age in years - adults&quot;</span>, <span class="dt">y  =</span><span class="st">&quot;BMI&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Comparing mean BMI by age &amp; gender groupings&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;Gender&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<p><img src="07-simple_regression_analysis_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>From this graph it appears that the fitted line for men has a lower intercept and also a more gradual slope. This suggests that on average women have a higher BMI at age 21 and their BMI increases at a faster rate between age 21 and age 40.</p>
</div>
<div id="exercises-5" class="section level2">
<h2><span class="header-section-number">7.10</span> Exercises</h2>
<p>So now that we have learned quite a bit about regression analysis, it’s time to put our knowledge to the test!</p>
<p><strong>1. What is the correlation between where a person lives, their total monthly take home pay, and their associated total monthly household food expenditure?</strong></p>
<p>Exercise 1 Answer</p>
<p><strong>2. Generally speaking (with a normal labour supply curve) people are willing to work more when they get paid more (after tax). Investigate this relationship by regressing “hours worked last week” on “individual take home pay” Have you estimated a labour supply function?</strong></p>
<p>Exercise 2 Answer</p>
<p><strong>3. It is a reasonable expectation that the bigger a residence is, the more that it costs to live in it. Is this true in the NIDS dataset? If so, how much more will an additional room cost? Interpret the data with a regression and then show a graph. What would happen if we didn’t condition on hhrestrict when graphing?</strong></p>
<p>Exercise 3 Answer</p>
<p><strong>4. Now, let’s consider whether the number of people in a family will determine the size of the house that it lives in. If so, an additional person is likely to make a family acquire how many more rooms (on average)? Please show the graph for this relationship.</strong></p>
<p>Exercise 4 Answer</p>
<p><strong>5. Eating out is considered to be a luxury. Is it reasonable to assume that as income goes up, money spent on eating out would go up too? See if this is the case in the NIDS</strong></p>
<p>So now that we have learned quite a bit about regression analysis, it’s time to put our knowledge to the test! 1. What is the correlation between where a person lives, their total monthly take home pay, and their associated total monthly household food expenditure?</p>
<p>Exercise 1 Answer</p>
</div>
<div id="exercise-1" class="section level2">
<h2><span class="header-section-number">7.11</span> Exercise</h2>
<p>So now that we have learned quite a bit about regression analysis, it’s time to put our knowledge to the test!</p>
<p><strong>1. What is the correlation between where a person lives, their total monthly take home pay, and their associated total monthly household food expenditure?</strong></p>
<p>Exercise 1 Answer</p>
<p><strong>2. Generally speaking (with a normal labour supply curve) people are willing to work more when they get paid more (after tax). Investigate this relationship by regressing “hours worked last week” on “individual take home pay” Have you estimated a labour supply function?</strong></p>
<p>Exercise 2 Answer</p>
<p><strong>3. It is a reasonable expectation that the bigger a residence is, the more that it costs to live in it. Is this true in the NIDS dataset? If so, how much more will an additional room cost? Interpret the data with a regression and then show a graph. What would happen if we didn’t condition on hhrestrict when graphing?</strong></p>
<p>Exercise 3 Answer</p>
<p><strong>4. Now, let’s consider whether the number of people in a family will determine the size of the house that it lives in. If so, an additional person is likely to make a family acquire how many more rooms (on average)? Please show the graph for this relationship.</strong></p>
<p>Exercise 4 Answer</p>
<p><strong>5. Eating out is considered to be a luxury. Is it reasonable to assume that as income goes up, money spent on eating out would go up too? See if this is the case in the NIDS dataset. If so, for every rand a family earns, how much is likely to be spent on eating out?</strong></p>
<p>Exercise 5 Answer</p>
</div>
<div id="exercise-answers-4" class="section level2">
<h2><span class="header-section-number">7.12</span> Exercise answers</h2>
</div>
<div id="appendix-a-analysis-of-variance-anova-table" class="section level2">
<h2><span class="header-section-number">7.13</span> Appendix A: Analysis of variance (anova) table</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(lm0)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: w1_h_expenditure
##               Df     Sum Sq    Mean Sq F value    Pr(&gt;F)    
## w1_hhincome    1 1.7838e+11 1.7838e+11    6612 &lt; 2.2e-16 ***
## Residuals   7303 1.9702e+11 2.6978e+07                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Although we are not particularly concerned with ANOVA tables in this chapter, it is nice to know the following definitions. SS (<code>Sum Sq</code>) stands for the sum‐of‐squares. The “Total” sum‐of‐squares (TSS) is the sum of the squared distances between each observation point (Y‐observed) and the mean value of Y (remember in this case our Y is <code>w1_h_expenditure</code>). The “Model” (<code>w1_hhincome</code>) sum‐of‐squares (also sometimes called “Explained” sum‐of‐squares) is the sum of the squared distances between the mean value of Y and the predicted values of Y generated by the “best‐fit” line (also known as Yhat). The <code>Residuals</code> sum‐of‐squares is the sum of the squared distances between each Y‐ observation point and our Yhat’s. Thus “Model”SS + “Resdiduals” SS = “Total” SS (or alternatively MSS + RSS = TSS).</p>
<p><img src="images/reg0.png" width="80%" /></p>
<p>Notice also that <code>Df</code> stands for degrees of freedom, which is number of observations in the sample minus the number of independent constraints. The number of degrees of freedom serves as a flexibility measure in the t distribution. <code>Mean Sq</code> is the mean of squares or simply the relevant SS divided by the corresponding df. The <code>F value</code> and <code>Pr(&gt;F)</code> will be explained in <a href="simple-regression-analysis.html#appendix-b-further-understanding-the-regression-results-table">Appendix B</a></p>
<p>Back to <a href="simple-regression-analysis.html#understanding-regression-output-tables">Understanding Regression Output Tables</a></p>
</div>
<div id="appendix-b-further-understanding-the-regression-results-table" class="section level2">
<h2><span class="header-section-number">7.14</span> Appendix B: Further understanding the regression results table</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(lm0)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = w1_h_expenditure ~ w1_hhincome, data = nids2)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -60739  -1231   -758     53 108202 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.115e+03  6.954e+01   16.03   &lt;2e-16 ***
## w1_hhincome 6.146e-01  7.558e-03   81.31   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5194 on 7303 degrees of freedom
## Multiple R-squared:  0.4752, Adjusted R-squared:  0.4751 
## F-statistic:  6612 on 1 and 7303 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Meaning behind each section of <code>summary()</code></strong></p>
<p><strong><code>Call</code></strong>: This is an R feature that shows what function and parameters were used to create the model.</p>
<p><strong><code>Residuals</code></strong>: Difference between what the model predicted and the actual value of y. This section provides a summary of the residuals - <code>Min</code>, <code>1Q</code>, <code>Median</code>,<code>3Q</code> and <code>Max</code></p>
<p><strong>Coefficients</strong>: These are the weights that minimize the sum of the square of the errors.</p>
<p>Under <code>coefficients</code>, we have the following:</p>
<p><code>Estimate</code>: these are the estimated weights or coeficient for each covariate. In our case, for <code>w1_hhincome</code> and the constant (<code>(Intercept)</code>)</p>
<p><code>Std. Error</code> is residual standard error divided by the square root of the sum of the square of that particular x variable.</p>
<p><code>t value</code>: is the value on the t distribution associated with our coefficients. That is <code>Estimate</code> divided by <code>Std. Error</code>.</p>
<p><code>Pr(&gt;|t|)</code>: is the probability that our statistic is greater than the critical value of 1.96. Look up your t value in a T distribution table with the given degrees of freedom. For both cases (<code>w1_hhincome</code> and <code>(Intercept)</code>), the probability that these coefficients are not different from the null hypothesis of zero, is basically none.</p>
<p><strong><code>Residual Standard Error</code></strong>: standard error of the residuals. It is a measure of the quality of a linear regression fit.</p>
<p><strong><code>Multiple R-Squared</code></strong>: is a measure of how much of the variance around Y does X account for. Because the lowest possible R-squared is 0.0 and the highest is 1.0, our R-squared of 0.4751 means that we are explaining just over 47% of the variance in total monthly household expenditures by using total monthly household income.</p>
<p><strong><code>Adjusted R-Squared</code></strong>: is just the R-squared adjusted by the degrees of freedom(We use this measure instead of <code>Multiple R-squared</code> when we have more than one independent variable)</p>
<p><strong><code>F-Statistic</code></strong>: stands for F distribution and it used test the overall statistical significance of the regression.</p>
<p>Back to <a href="simple-regression-analysis.html#understanding-regression-output-tables">Understanding Regression Output Tables</a></p>
</div>
<div id="session-information-5" class="section level2">
<h2><span class="header-section-number">7.15</span> Session information</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(<span class="kw">sessionInfo</span>(), <span class="dt">locale =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## R version 3.5.1 (2018-07-02)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 7 x64 (build 7601) Service Pack 1
## 
## Matrix products: default
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] stargazer_5.2.2 ggalt_0.4.0     scales_0.5.0    bindrcpp_0.2.2 
##  [5] forcats_0.3.0   stringr_1.3.1   dplyr_0.7.6     purrr_0.2.5    
##  [9] readr_1.1.1     tidyr_0.8.1     tibble_1.4.2    ggplot2_3.0.0  
## [13] tidyverse_1.2.1 foreign_0.8-70 
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.17       lubridate_1.7.4    lattice_0.20-35   
##  [4] assertthat_0.2.0   rprojroot_1.3-2    digest_0.6.15     
##  [7] proj4_1.0-8        psych_1.8.4        utf8_1.1.4        
## [10] R6_2.2.2           cellranger_1.1.0   plyr_1.8.4        
## [13] backports_1.1.2    evaluate_0.10.1    httr_1.3.1        
## [16] pillar_1.2.3       rlang_0.2.1        lazyeval_0.2.1    
## [19] readxl_1.1.0       rstudioapi_0.7     extrafontdb_1.0   
## [22] Matrix_1.2-14      rmarkdown_1.10     labeling_0.3      
## [25] extrafont_0.17     munsell_0.5.0      broom_0.4.5       
## [28] compiler_3.5.1     modelr_0.1.2       xfun_0.2          
## [31] pkgconfig_2.0.1    mnormt_1.5-5       mgcv_1.8-24       
## [34] htmltools_0.3.6    tidyselect_0.2.4   bookdown_0.7      
## [37] crayon_1.3.4       withr_2.1.2        MASS_7.3-50       
## [40] grid_3.5.1         nlme_3.1-137       jsonlite_1.5      
## [43] Rttf2pt1_1.3.7     gtable_0.2.0       magrittr_1.5      
## [46] KernSmooth_2.23-15 cli_1.0.0          stringi_1.1.7     
## [49] reshape2_1.4.3     xml2_1.2.0         ash_1.0-15        
## [52] RColorBrewer_1.1-2 tools_3.5.1        glue_1.2.0        
## [55] maps_3.3.0         hms_0.4.2          parallel_3.5.1    
## [58] yaml_2.1.19        colorspace_1.3-2   rvest_0.3.2       
## [61] knitr_1.20         bindr_0.1.1        haven_1.1.2</code></pre>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-R-ggalt">
<p>Rudis, Bob, Ben Bolker, and Jan Schulz. 2017. <em>Ggalt: Extra Coordinate Systems, ’Geoms’, Statistical Transformations, Scales and Fonts for ’Ggplot2’</em>. <a href="https://CRAN.R-project.org/package=ggalt" class="uri">https://CRAN.R-project.org/package=ggalt</a>.</p>
</div>
<div id="ref-R-stargazer">
<p>Hlavac, Marek. 2018. <em>Stargazer: Well-Formatted Regression and Summary Statistics Tables</em>. <a href="https://CRAN.R-project.org/package=stargazer" class="uri">https://CRAN.R-project.org/package=stargazer</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="bivariate-analysis-cross-tabs.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-regression-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
